name: Run back end tests
on:
  workflow_dispatch:
  repository_dispatch:
    types: [beprems/bo_traitement_agent]

jobs:
  bo_traitement_agent-test-run:
#    if: ('beprems/bo_traitement_agent' == github.event.action)
    runs-on: ubuntu-latest
    env:
      INTERNAL_API_URL: 'http://app.local'
      INTERNAL_API_APP_ID: 'app_id'
      INTERNAL_API_APP_KEY: 'app_key'
      APP_ENV: 'test'

    steps:
      - name: Checkout repo ${{ github.event.action }}
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.action }}
          ref: ${{ github.event.client_payload.branch }}
          token: ${{ secrets.GH_PAT }}
#
#      - name: Setup GitHub SSH
#        uses: MrSquaare/ssh-setup-action@v1
#        with:
#          host: github.com
#          private-key: ${{ secrets.SSH_GITHUB_PRIVATE_KEY }}
#          private-key-name: ssh_gitHub

      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: php-actions/composer@v5
        with:
          php-version: 7.4
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo, bcmath, gettext
          ssh_key: ${{ secrets.SSH_GITHUB_PRIVATE_KEY }}
          ssh_key_pub: ${{ secrets.SSH_GITHUB_PUBLIC_KEY }}

#      - name: Install dependencies
#        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Generate JWT
        run: bin/console lexik:jwt:generate-keypair --skip-if-exists

      - name: debug
        run: ls -la vendor/kyc
        
      - name: Run test
        run: php bin/phpunit
        
     
