name: Merge Release to monolith_pitech

on:
  pull_request:
    types:
      - closed
    branches:
      - release
  workflow_dispatch:

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create pull request
        run: gh pr create -B monolith_pitech -H release --title 'Merge release into monolith_pitech' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo The PR was merged
      
