name: Run front end tests
on:
  repository_dispatch:
    types: [beprems/front_traitement_agent]

jobs:
  front-traitement-agent-cypress-run:
    runs-on: ubuntu-latest
    env:
      VITE_API_BASE_URL: 'https://back-bo-traitement-dev.wks-recette.com/api/v1'
      VITE_AUTH_TOKEN: 'X-Auth-Token'
      REACT_APP_API_BASE_URL: 'https://back-bo-traitement-dev.wks-recette.com/api/v1'
      REACT_APP_AUTH_TOKEN: 'X-Auth-Token'
      
    steps:
      - name: Checkout repo ${{ github.event.action }}
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.action }}
          ref: ${{ github.event.client_payload.branch }}
          token: ${{ secrets.GH_PAT }}
      
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'
      
      - name: Setup GitHub SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_GITHUB_PRIVATE_KEY }}
          private-key-name: ssh_gitHub
      
      - name: Run npm install
        run: |
          npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
          
      - name: Upload failed tests screenshots
        uses: actions/upload-artifact@v3.1.0
        if: failure()
        with:
          name: failed-tests-screenshots
          path: cypress/.results/screenshots
          retention-days: 1
