# This is a basic workflow to help you get started with Actions

name: Run tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ recette, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: beprems/KYB-lbp-front/
          ref: develop
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT

      - uses: actions/setup-node@v2
        with: 
          node-version: 14

      - name: Create env file
        run: cp .env.dist .env.test
        
      - name: Run npm install
        run: npm ci
        
      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test-ci