name: Run tests
on:
  pull_request:
    branches: [ recette, develop ]
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    if: ('beprems/KYB-white-label' == github.event.action) || ('beprems/KYB-lbp-front' == github.event.action)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo ${{ github.event.action }}
       uses: actions/checkout@v2
       with:
         repository: ${{ github.event.action }}
         ref: develop
         token: ${{ secrets.GH_PAT }}
      
      - uses: actions/setup-node@v2
       with: 
         node-version: '14'
      
      - name: Setup GitHub SSH
       uses: MrSquaare/ssh-setup-action@v1
       with:
         host: github.com
         private-key: ${{ secrets.SSH_GITHUB_PRIVATE_KEY }}
         private-key-name: ssh_gitHub
      
      - name: Create env file
       run: cp .env.dist .env.test
      
      - name: Run npm install
       run: npm ci
      
      - name: Run lint
       run: npm run lint
      
      - name: Run tests
       run: npm run test-ci
