name: Run tests
on:
  pull_request:
    branches: [ recette, develop ]
  workflow_dispatch:
  repository_dispatch:

jobs:
  front-traitement-agent-cypress-run:
    if: ('beprems/front_traitement_agent' == github.event.action)
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_BASE_URL: 'https://back-bo-traitement-dev.wks-recette.com/api/v1'
      REACT_APP_AUTH_TOKEN: 'X-Auth-Token'
      
    steps:
      - name: Checkout repo ${{ github.event.action }}
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.action }}
          ref: ${{ github.event.client_payload.branch }}
          token: ${{ secrets.GH_PAT }}
      
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'
      
      - name: Setup GitHub SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_GITHUB_PRIVATE_KEY }}
          private-key-name: ssh_gitHub
      
      - name: Run npm install
        run: |
          npm ci
          echo '${{ toJSON(env) }}'

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
  
  bo_traitement_agent-test-run:
    if: ('beprems/bo_traitement_agent' == github.event.action)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo ${{ github.event.action }}
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.action }}
          ref: ${{ github.event.client_payload.branch }}
          token: ${{ secrets.GH_PAT }}
          
      - name: Setup GitHub SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_GITHUB_PRIVATE_KEY }}
          private-key-name: ssh_gitHub

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test
        run: php bin/phpunit
      

